# Generated by Django 4.1.7 on 2023-03-31 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayingGuest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_details',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PayingGuest.pg'),
        ),
    ]
