# Generated by Django 4.1.7 on 2023-04-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayingGuest', '0002_pg_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='pg_addres',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='pg',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
