# Generated by Django 4.1.7 on 2023-04-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
